[package]
name = "propus"
version = "0.1.0"
edition = "2021"
description = "Static site builder for Gemini/Gemtext sites"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tera = "1"
time = "0.3"
tejat = { path = "../tejat" }
