[package]
name = "alhena"
version = "0.1.0"
edition = "2021"
description = "Server library and software for Gemini"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
